name: flutter_application_11
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  uuid: ^3.0.6
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  flutter_rating_bar: ^4.0.1
  
  intl: ^0.19.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/cover.png
